/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.MouseInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Megatron
 */
public class Creditos extends javax.swing.JFrame {

    /**
     * Creates new form Creditos
     */
    JFrame pai;
    
    public Creditos(JFrame parent) {
        initComponents();
        
        pai = parent;
        new Animacao().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1284, 747));
        setMinimumSize(new java.awt.Dimension(1284, 747));
        setPreferredSize(new java.awt.Dimension(1284, 747));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/HumanoPadrão.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(890, 490, 230, 190);

        btSair.setBackground(new java.awt.Color(50, 50, 50));
        btSair.setForeground(new java.awt.Color(255, 255, 255));
        btSair.setText("Voltar");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        jPanel1.add(btSair);
        btSair.setBounds(1130, 650, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Creditos.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        pai.setLocation(getX(),getY());
        pai.setVisible(true);
        dispose();
    }//GEN-LAST:event_btSairMouseClicked

    /**
     * @param args the command line arguments
     */
    
    class Animacao extends Thread
    {
        
        @Override
        public void run()
        {
            try {
                sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
            }
            while(isVisible())
            {
                
                try {
                    sleep(1);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                jLabel1.setLocation(jLabel1.getX(),jLabel1.getY()+50);
                
                try {
                    sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
                }
                jLabel1.setLocation(jLabel1.getX(),jLabel1.getY()-50);
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/Resources/Humano1mao1.png")));
                
                try {
                    sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
                }
                jLabel1.setLocation(jLabel1.getX(),jLabel1.getY()+50);
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/Resources/Humano1mao2.png")));
                
                try {
                    sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
                }
                jLabel1.setLocation(jLabel1.getX(),jLabel1.getY()-50);
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/Resources/Humano2mao1.png")));
                
                try {
                    sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
                }
                jLabel1.setLocation(jLabel1.getX(),jLabel1.getY()+50);
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/Resources/Humano2mao2.png")));
                
                try {
                    sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Creditos.class.getName()).log(Level.SEVERE, null, ex);
                }
                jLabel1.setLocation(jLabel1.getX(),jLabel1.getY()-50);
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/Resources/HumanoPadrão.png")));
                
            }
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
