/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerPersonagem;

/**
 *
 * @author Megatron
 */
public class MenuPrincipalRPG extends javax.swing.JFrame {

    protected ControllerPersonagem controlPerso = new ControllerPersonagem();
    
    
    public MenuPrincipalRPG() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        lbAvisoBDFull = new javax.swing.JLabel();
        btNovoJogo = new javax.swing.JButton();
        btCarregarJogo = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1282, 747));
        setMinimumSize(new java.awt.Dimension(1282, 747));
        setPreferredSize(new java.awt.Dimension(1282, 747));
        setResizable(false);
        setSize(new java.awt.Dimension(1282, 747));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        MainMenu.setMaximumSize(new java.awt.Dimension(1280, 720));
        MainMenu.setMinimumSize(new java.awt.Dimension(1280, 720));
        MainMenu.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainMenu.setLayout(null);

        lbAvisoBDFull.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAvisoBDFull.setForeground(new java.awt.Color(255, 255, 255));
        lbAvisoBDFull.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMenu.add(lbAvisoBDFull);
        lbAvisoBDFull.setBounds(510, 140, 390, 30);

        btNovoJogo.setBackground(new java.awt.Color(50, 50, 50));
        btNovoJogo.setForeground(new java.awt.Color(255, 255, 255));
        btNovoJogo.setText("Novo Jogo");
        btNovoJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNovoJogoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNovoJogoMouseExited(evt);
            }
        });
        btNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoJogoActionPerformed(evt);
            }
        });
        MainMenu.add(btNovoJogo);
        btNovoJogo.setBounds(590, 70, 150, 50);

        btCarregarJogo.setBackground(new java.awt.Color(50, 50, 50));
        btCarregarJogo.setForeground(new java.awt.Color(255, 255, 255));
        btCarregarJogo.setText("Carregar Jogo");
        btCarregarJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCarregarJogoMouseClicked(evt);
            }
        });
        btCarregarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarJogoActionPerformed(evt);
            }
        });
        MainMenu.add(btCarregarJogo);
        btCarregarJogo.setBounds(740, 230, 150, 50);

        btSair.setBackground(new java.awt.Color(50, 50, 50));
        btSair.setForeground(new java.awt.Color(255, 255, 255));
        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        MainMenu.add(btSair);
        btSair.setBounds(740, 430, 150, 50);

        jButton1.setBackground(new java.awt.Color(50, 50, 50));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Créditos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        MainMenu.add(jButton1);
        jButton1.setBounds(590, 610, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Tela_inicial.png"))); // NOI18N
        MainMenu.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 721);

        getContentPane().add(MainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btSairMouseClicked

    private void btCarregarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarJogoActionPerformed
        
    }//GEN-LAST:event_btCarregarJogoActionPerformed

    private void btNovoJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoJogoMouseClicked
        //if(controlPerso.bdIsFull())
        //{
        //    lbAvisoBDFull.setText("A lista de personagens salvos está cheia!");
        //}
        //else
        //{
            lbAvisoBDFull.setText("");
            CriacaoDePersonagem cp = new CriacaoDePersonagem(controlPerso,this);
            cp.setVisible(true);
            cp.setLocation(getX(),getY());
            this.setVisible(false);
        //}
    }//GEN-LAST:event_btNovoJogoMouseClicked

    private void btNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNovoJogoActionPerformed

    private void btCarregarJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCarregarJogoMouseClicked
        MenuSelecaoDePersonagem sp = new MenuSelecaoDePersonagem(controlPerso, this);
        sp.setVisible(true);
        sp.setLocation(getX(),getY());
        this.setVisible(false);
    }//GEN-LAST:event_btCarregarJogoMouseClicked

    private void btNovoJogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoJogoMouseExited
        lbAvisoBDFull.setText("");
    }//GEN-LAST:event_btNovoJogoMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Creditos sp = new Creditos(this);
        sp.setVisible(true);
        sp.setLocation(getX(),getY());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalRPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalRPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalRPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalRPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalRPG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton btCarregarJogo;
    private javax.swing.JButton btNovoJogo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAvisoBDFull;
    // End of variables declaration//GEN-END:variables
}
